version: '3.7'
services:
  postgresql:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
       - C:\Users\Professional\Desktop\Aga7\docker\data:/var/lib/postgresql
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: mysecretpassword